[package]
name = "termos"
description = "Terminal user interface for Azure Cosmos DB"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
azure_core.workspace = true
azure_data_cosmos.workspace = true
azure_identity.workspace = true
clap.workspace = true
dirs = "7.0.0"
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
ratatui = "0.30.2"
crossterm = { version = "0.29.0", features = ["event-stream"] }

[dev-dependencies]
tempfile = "3.27.0"
