[package]
name = "cosmoscli"
description = "Command line tool for Azure Cosmos DB"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cosmos-core = { path = "../cosmos-core", features = ["clap"] }
anyhow.workspace = true
async-trait.workspace = true
azure_core.workspace = true
azure_data_cosmos.workspace = true
azure_identity.workspace = true
clap.workspace = true
comfy-table.workspace = true
dialoguer.workspace = true
futures.workspace = true
reqwest.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
cosmos-core = { path = "../cosmos-core", features = ["clap", "test-support"] }
tempfile = "3.27.0"
